# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: postgres
    expose:
      - 5432:5432
