# Use postgres/example user/password credentials
version: '3.9'

services:
  main:
    image: assesment:0.0.1-SNAPSHOT
    expose:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: yanch
    expose:
      - 5432:5432